name: gigglify_fl
description: "A Jokes App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # core
  auto_route: ^9.3.0+1
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # eye-candy
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.19.0
  ionicons: ^0.2.2
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^9.3.1
  build_runner: ^2.4.14 # dart run build_runner build --delete-conflicting-outputs
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env

flutter_intl:
  enabled: true
  output_dir: lib/l10n/generated
