name: gigglify_fl
description: "A Jokes App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # core
  auto_route: ^9.3.0+1
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  realm: ^20.0.1 # dart run realm generate
  share_plus: ^10.1.4
  shared_preferences: ^2.3.5

  # eye-candy
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  ionicons: ^0.2.2
  modal_bottom_sheet: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: # dart run build_runner build --delete-conflicting-outputs
  build_runner: ^2.4.14 # dart run build_runner build --delete-conflicting-outputs
  flutter_lints: ^5.0.0
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env

flutter_intl:
  enabled: true
  output_dir: lib/l10n/generated
